services:

  service-a:
    build: ./serviceA
    container_name: service-a
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - service-b
    networks:
      - elk-network
    volumes:
      - ./logs:/logs   # writes logs here

  service-b:
    build: ./serviceB
    container_name: service-b
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - service-c
    networks:
      - elk-network
    volumes:
      - ./logs:/logs

  service-c:
    build: ./serviceC
    container_name: service-c
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - filebeat
      - logstash
    networks:
      - elk-network
    volumes:
      - ./logs:/logs

  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      - xpack.security.enabled=false  # Disable security for local development
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - elk-network

  logstash:
    image: logstash:8.17.1
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '5044:5044'
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - elk-network

  kibana:
    image: kibana:8.17.1
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.1
    container_name: filebeat
    user: root
    environment:
      - BEAT_STRICT_PERMS=false
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro # mount logs, read-only
      - ./data/filebeat:/usr/share/filebeat/data   # persist registry
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge

volumes:
  elastic_data: {}